server:
  port: 9584

security:
  oauth2:
    client:
      clientId: 9462323553840800
      clientSecret: aacfc9ca4c26e02cb284939bfc45c970
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
